/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PredefinedReward = ((
  | {
      rewardConfigType?: "globalRewardSetup";
      globalRewardKey: PickAGlobalReward;
    }
  | {
      rewardConfigType?: "programRewardSetup";
      rewardType: "PCT_DISCOUNT" | "CREDIT" | "FUELTANK" | "INTEGRATION";
    }
) &
  (
    | {
        rewardType?: "PCT_DISCOUNT";
        amount: DiscountPercent;
        validityDuration?: DurationRewardIsValid;
        pendingDuration?: DurationRewardIsPending;
      }
    | {
        rewardType?: "CREDIT";
        amount: CreditAmount;
        unit: RewardUnit;
        validityDuration?: DurationRewardIsValid;
        pendingDuration?: DurationRewardIsPending;
      }
    | ((
        | {
            fuelTankType?: "PCT_DISCOUNT";
            amount: DiscountPercent1;
            validityDuration?: DurationRewardIsValid;
            pendingDuration?: DurationRewardIsPending;
            allowsInstantAccess: AllowInstantAccess;
          }
        | {
            fuelTankType?: "CREDIT";
            amount: CreditAmount1;
            unit: RewardUnit1;
            allowsInstantAccess: AllowInstantAccess1;
          }
      ) & {
        rewardType?: "FUELTANK";
        fuelTankType: RewardType;
        validityDuration?: DurationRewardIsValid;
        pendingDuration?: DurationRewardIsPending;
        allowsInstantAccess?: AllowInstantAccess2;
      })
    | {
        rewardType?: "INTEGRATION";
        amount: CreditAmount2;
        unit?: GiftCardType;
        integrationId?: IntegrationIdentifier;
        integrationSettings?: IntegrationSettings;
        pendingDuration?: DurationRewardIsPending;
      }
  )) & {
  name?: Name;
  key?: Key;
  rewardType?: "PCT_DISCOUNT" | "CREDIT" | "FUELTANK" | "INTEGRATION";
  rewardConfigType: "globalRewardSetup" | "programRewardSetup";
};
export type PickAGlobalReward = string;
export type DiscountPercent = number;
/**
 * This interface was referenced by `Reward`'s JSON-Schema
 * via the `definition` "validityDuration".
 */
export type DurationRewardIsValid = string;
/**
 * This interface was referenced by `Reward`'s JSON-Schema
 * via the `definition` "pendingDuration".
 */
export type DurationRewardIsPending = string;
export type CreditAmount = number;
export type RewardUnit = string;
export type DiscountPercent1 = number;
export type AllowInstantAccess = boolean;
export type CreditAmount1 = number;
export type RewardUnit1 = string;
export type AllowInstantAccess1 = boolean;
export type RewardType = "PCT_DISCOUNT" | "CREDIT";
export type AllowInstantAccess2 = boolean;
export type CreditAmount2 = number;
export type GiftCardType = string;
export type IntegrationIdentifier = string;
export type EmailTemplateID = string;
export type Name = string;
export type Key = string;

/**
 * This interface was referenced by `Reward`'s JSON-Schema
 * via the `definition` "integrationSettings".
 */
export interface IntegrationSettings {
  templateId?: EmailTemplateID;
  giftId?: string;
  utid?: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "reward".
 */
export interface Reward {
  [k: string]: unknown;
}
